name:                c

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  extra-libraries: small

executables:
  c-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c
